[build]
  publish = "dist/"

[context.production]
  command = "yarn build"

[context.deploy-preview]
  command = "yarn build"

[context.branch-deploy]
  command = "yarn build"

[[redirects]]
  from = "/asd"
  to = "https://ishikawa.rakusate.com/"
  status = 301
  force = true