[build]
  publish = "dist/"

[context.production]
  command = "yarn build"

[context.deploy-preview]
  command = "yarn build"

[context.branch-deploy]
  command = "yarn build"

[[redirects]]
  from = ""
  to = "https://ishikawa.rakusate.com/"
  status = 301

[[redirects]]
  from = "/"
  to = "https://ishikawa.rakusate.com/"
  status = 301

[[redirects]]
  from = "https://inspiring-colden-9b53a0.netlify.app/"
  to = "https://ishikawa.rakusate.com/"
  status = 301

[[redirects]]
  from = "/*"
  to = "https://ishikawa.rakusate.com/"
  status = 301