name: Netlify Build

on:
  schedule:
    - cron: '10 * * * *'

jobs:
  build:
    name: Request Build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: curl -X POST -d {} ${{ secrets.WEBHOOK_URL }}